#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  tLaunch,        sensorTouch)
#pragma config(Sensor, dgtl2,  tBall,          sensorTouch)
#pragma config(Motor,  port2,           RF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           launcher,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intake,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * @file    main.c
 * @brief   This file contains the base for competiton code.
 * @details The three sections include Pre-Auton, Auton, and User
 *          Control.
 *
 * @author		Sean Kelley      sgtkode01@gmail.com
 * @author		Bernard Suwirjo  bsuwirjo@gmail.com
 */


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// all functions for competition code
#include "functions.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period before autonomous when bot cannot move, but minimal code can run
 */
void pre_auton()
{
 bStopTasksBetweenModes = true;
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when bot is using only code to operate.
 */
task autonomous(){
	runLauncher(4, 118);
	forwardSeconds(1.5, 118);
	runIntake(2);
	backwardSeconds(1.5, 118);
	runLauncher(4, 118);
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
0.
/**
 * Period of match when driver controls the bot
 */
task usercontrol(){


while(true)
{


		//	clearline();
	//		mainLCD();
			drive();
			intakeCont();
			launcherCont();

}
}
