#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  tLaunch,        sensorTouch)
#pragma config(Sensor, dgtl2,  pn1,            sensorTouch)
#pragma config(Sensor, dgtl3,  tBall,          sensorNone)
#pragma config(Motor,  port2,           intake1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           launcher1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           launcher2,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * @file    main.c
 * @brief   This file contains the base for competiton code.
 * @details The three sections include Pre-Auton, Auton, and User
 *          Control.
 *
 * @author		Sean Kelley      sgtkode01@gmail.com
 * @author		Bernard Suwirjo  bsuwirjo@gmail.com
 */


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// all functions for competition code
#include "functions.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period before autonomous when bot cannot move, but minimal code can run
 */
void pre_auton()
{
 bStopTasksBetweenModes = true;
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when bot is using only code to operate.
 */
task autonomous(){
	runLauncherSec(1.64);
	runIntake2(0.7);
	wait10Msec(0.7);
	runLauncherSec(1.64);
	runIntake2(1.5);
	wait10Msec(0.7);
	runLauncherSec(1.64);
	runIntake(1);
	runIntake2(2.1);
	runLauncherSec(1.64);
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
/////////////////////////////////////////////////////////////////////////////////////////
/**
 * Period of match when driver controls the bot
 */
task usercontrol(){
	clearline();
	SensorValue[pn1] = 1;
	while(true)
  {
		  	mainLCD();
				drive();
				intakeCont();
				intakeCont2();
				launcherCont();
				pnCont();
	}
}
